services:
  postgres:
    image: postgres:16
    container_name: plantsocial_db
    environment:
      POSTGRES_DB: plantsocial
      POSTGRES_USER: plantsocial_user
      POSTGRES_PASSWORD: plantsocial_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
